name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # runs daily at midnight UTC

permissions:
  contents: write

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:

          # Authentication
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}

          # Meta Tweaks
          API_BASE_URL: "https://wakatime.com/api"
          REPOSITORY: "AmrTarek7/AmrTarek7"

          # Content Tweaks
          SHOW_TITLE: "true"
          SECTION_NAME: "waka"
          BLOCKS: "->"
          CODE_LANG: "txt"
          TIME_RANGE: "last_7_days"
          LANG_COUNT: "10"
          SHOW_TIME: "true"
          SHOW_TOTAL: "true"
          SHOW_MASKED_TIME: "false"
          STOP_AT_OTHER: "true"
          IGNORED_LANGUAGES: "YAML JSON TOML"

          # Commit Tweaks
          COMMIT_MESSAGE: "ðŸš€ Updated WakaReadme stats"
          TARGET_BRANCH: "main"
          TARGET_PATH: "README.md"
          COMMITTER_NAME: "Amr Tarek Bot"
          COMMITTER_EMAIL: "amryousef04@gmail.com"
          AUTHOR_NAME: "Amr Tarek"
          AUTHOR_EMAIL: "amryousef04@gmail.com"
